name: commitlint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run-commitlint-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.17.0
      - name: Install dependencies
        run: npm install -g @commitlint/{cli,config-conventional}
      - name: Validate all commits from PR
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose
